site_name: SFDX Batch Orchestrator
repo_url: https://github.com/dschibster/sfdx-batch-orchestrator
repo_name: dschibster/sfdx-batch-orchestrator

nav:
    - Introduction: 'index.md'
    - 'installation.md'
    - 'code.md'
    - 'logging.md'
    - 'usage.md'

theme:
  name: material
  logo: https://github.com/dschibster/sfdx-batch-orchestrator/blob/master/resources/batchorchestratorlogo.png?raw=true

  palette: 
    scheme: slate
    primary: blue

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  